#!/usr/bin/env python

from model import Model
from os import PathLike
from pprint import pprint
import csv

def load_iris_dataset(path: PathLike = "dataset/iris.csv"):
    dataset = []

    with open(path, "r", encoding="utf-8") as f:
        reader = csv.reader(f)

        for row in reader:
            dataset.append(row)
    
    dataset.pop(0)
    return parse_iris_dataset(dataset)

def parse_iris_dataset(dataset: list[list[str]]):
    return [[float(data[0]), float(data[1]), float(data[2]), float(data[3]), data[4]] for data in dataset]

if __name__ == "__main__":
    dataset = load_iris_dataset()
    model = Model()
