#!/usr/bin/env python

from model import Model
import dataset

if __name__ == "__main__":
    dt = dataset.load(lambda data: [int(float(data[0])), data[1], data[2], float(data[3]), int(data[4]), data[5], float(data[6]), data[7], float(data[8]), float(data[9]), float(data[10]), int(data[11]), data[12], int(data[13])], "dataset/loan.csv")
    dt = dataset.enumize(dt)
    dt = dataset.split(dt, n=2*5) 
    dt = { "train": dt[0], "test": dt[1] }

    model = Model()
    model.fit([data[:-1] for data in dt["train"]], [data[-1] for data in dt["train"]])

    correct = 0
    for data in dt["test"]:
        predicted = model.classify(data[:-1])
        actual = data[-1]
        correct += predicted == actual
    
    print(f'Accuracy: {(100 / (len(dt["test"]) / correct)):.2f}%')
